
export const DEFAULT_ADDRESS = 0x60


export const REGISTER = {
  DEVICE_STATUS: 0,
  INTERRUPT_STATUS_STICKY: 1,
  INTERRUPT_STATUS_MASK: 2,
  OUTPUT_ENABLE_CONTROL: 3,
  // 4 - 8 Reserved
  OEB_PIN_ENABLED_CONTROL: 9,
  // 10 - 14 Reserved
  PLL_INPUT_SOURCE: 15,
  CLK0_CONTROL: 16,
  CLK1_CONTROL: 17,
  CLK2_CONTROL: 18,
  CLK3_CONTROL: 19,
  CLK4_CONTROL: 20,
  CLK5_CONTROL: 21,
  CLK6_CONTROL: 22,
  CLK7_CONTROL: 23,
  //
  CLK_3_0_DISABLE_STATE : 24,
  CLK_7_4_DISABLE_STATE : 25,
  // 26 - 41 PLL, MultiSynth, and output clock delay offset Configuration Registers.
  // MultiSynth 0
  MULTSYNTH_0_PARAMETERS: 42,
  // MULTSYNTH_0_PARAMETERS: 43,
  // MULTSYNTH_0_PARAMETERS: 44,
  // MULTSYNTH_0_PARAMETERS: 45,
  // MULTSYNTH_0_PARAMETERS: 46,
  // MULTSYNTH_0_PARAMETERS: 47,
  // MULTSYNTH_0_PARAMETERS: 48,
  // MULTSYNTH_0_PARAMETERS: 49,
  // MultiSynth 1
  MULTSYNTH_1_PARAMETERS: 50,
  // MULTSYNTH_1_PARAMETERS: 51,
  // MULTSYNTH_1_PARAMETERS: 52,
  // MULTSYNTH_1_PARAMETERS: 53,
  // MULTSYNTH_1_PARAMETERS: 54,
  // MULTSYNTH_1_PARAMETERS: 55,
  // MULTSYNTH_1_PARAMETERS: 56,
  // MULTSYNTH_1_PARAMETERS: 57,
  // MULTSYNTH_1_PARAMETERS: 58,
  // MULTSYNTH_1_PARAMETERS: 59,
  // MultiSynth 2
  MULTSYNTH_2_PARAMETERS: 60,
  // MULTSYNTH_2_PARAMETERS: 61,
  // MULTSYNTH_2_PARAMETERS: 62,
  // MULTSYNTH_2_PARAMETERS: 63,
  // MULTSYNTH_2_PARAMETERS: 64,
  // MULTSYNTH_2_PARAMETERS: 65,
  // MultiSynth 3
  MULTSYNTH_3_PARAMETERS: 66,
  // MULTSYNTH_3_PARAMETERS: 67,
  // MULTSYNTH_3_PARAMETERS: 68,
  // MULTSYNTH_3_PARAMETERS: 69,
  // MULTSYNTH_3_PARAMETERS: 70,
  // MULTSYNTH_3_PARAMETERS: 71,
  // MULTSYNTH_3_PARAMETERS: 72,
  // MULTSYNTH_3_PARAMETERS: 73,
  // MultiSynth 4
  MULTSYNTH_4_PARAMETERS: 74,
  // MULTSYNTH_4_PARAMETERS: 75,
  // MULTSYNTH_4_PARAMETERS: 76,
  // MULTSYNTH_4_PARAMETERS: 77,
  // MULTSYNTH_4_PARAMETERS: 78,
  // MULTSYNTH_4_PARAMETERS: 79,
  // MULTSYNTH_4_PARAMETERS: 80,
  // MULTSYNTH_4_PARAMETERS: 81,
  // MultiSynth 5
  MULTSYNTH_5_PARAMETERS: 82,
  // MULTSYNTH_5_PARAMETERS: 83,
  // MULTSYNTH_5_PARAMETERS: 84,
  // MULTSYNTH_5_PARAMETERS: 85,
  // MULTSYNTH_5_PARAMETERS: 86,
  // MULTSYNTH_5_PARAMETERS: 87,
  // MULTSYNTH_5_PARAMETERS: 88,
  // MULTSYNTH_5_PARAMETERS: 89,
  // MultiSynth 6
  MULTSYNTH_6_PARAMETERS: 90,
  // MultiSynth 7
  MULTSYNTH_7_PARAMETERS: 91,
  //
  CLOCK_6_AND_7_OUTPUT_DIVIDER: 92,
  // 93 - 164 PLL, MultiSynth, and output clock delay offset Configuration Registers
  CLK0_INITIAL_PHASE_OFFSET: 165,
  CLK1_INITIAL_PHASE_OFFSET: 166,
  CLK2_INITIAL_PHASE_OFFSET: 167,
  CLK3_INITIAL_PHASE_OFFSET: 168,
  CLK4_INITIAL_PHASE_OFFSET: 169,
  CLK5_INITIAL_PHASE_OFFSET: 170,
  // 171
  // 172
  // 173 - 176 Reserved
  PLL_RESET: 177,
  // 178 – 182 Reserved
  CRYSTAL_INTERNAL_LOAD_CAPACITANCE: 183,
  // 184 – 255 Reserved
}